### ISSUE TITLE
Macros aren't changed on loadout switch

### ISSUE THREAD

**Issue by phem0r** [Breeni/BtWLoadouts#39]
Hello, hope you're well.

Last season, i had 2 macro's, one for using Spear of Bastion+ava+reck+trinket (im lazy) for ST content and then a second for Thunderous Roar+ava+reck+trinket for MT content.

I had these setup in the usual macros and then had 2 saved Action Bars set where one has the ST macro and the other had the MT macro so that when i switch Loadout, it'd give me the right action bar for if i was going to ST or MT etc.

The button no longer seems to switch when loading between loadouts, it stays on whatever i had it on last. I've deleted the loadouts, action bars etc and recreated but no difference..

Any ideas?

Thanks!

**Comment by Breeni** [comment]
There were some changes in 10.2 that has made handling macros harder. I've pushed a new build though (v1.15.5) that should fix this issue though, please let me know if it persists.

**Comment by phem0r** [comment]
> There were some changes in 10.2 that has made handling macros harder. I've pushed a new build though (v1.15.5) that should fix this issue though, please let me know if it persists.

Thank you for your response Breeni, just updated but unfortunately it has not resolved the issue.

**Comment by Breeni** [comment]
If you updated through Curseforge or similar can you please check the version number, there is a chance they are still downloading the previous versions from yesterday

**Comment by phem0r** [comment]
> If you updated through Curseforge or similar can you please check the version number, there is a chance they are still downloading the previous versions from yesterday

There we go, you're awesome, thank you!!
